import CryptoKit
import Foundation
import Testing
@testable import PhotoCore

/// Cross-checks the `Sources/PhotoCore/AdobeProfile/` port against fixtures
/// generated by the Python prototype
/// (`.photobench/engine-research-20260922/dcp-base-prototype/scripts/run_all.py`,
/// header-offset-corrected per `CORRECTION.md`) in `Tests/Fixtures/phase1/`,
/// plus a handful of self-contained property tests that need no external
/// asset.
///
/// Tests that need the real "Panasonic DC-S5 Adobe Standard.dcp" / "Adobe
/// Color.xmp" assets (never checked into this repo -- see
/// `AdobeProfileLocator`) skip gracefully (early `return`, no
/// `Issue.record`) with a printed reason when those assets are not
/// installed on the machine running the tests.
struct AdobeProfileTests {
    // MARK: - Fixture loading

    private var projectRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // AdobeProfileTests.swift -> PhotoCoreTests/
            .deletingLastPathComponent() // -> Tests/
            .deletingLastPathComponent() // -> repo root
    }

    private func fixtureURL(_ name: String) -> URL {
        projectRoot.appendingPathComponent("Tests/Fixtures/phase1/\(name)")
    }

    private func loadFixture<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        let data = try Data(contentsOf: fixtureURL(name))
        return try JSONDecoder().decode(T.self, from: data)
    }

    // MARK: - Real-asset loading (skips gracefully when unavailable)

    private func loadRealDCP() -> DCPProfile? {
        guard let located = AdobeProfileLocator().locateDCP(uniqueCameraModel: "Panasonic DC-S5") else {
            print("SKIP: Panasonic DC-S5 Adobe StandardのDCPが見つからないため、この環境ではスキップします。")
            return nil
        }
        return located.profile
    }

    private func loadRealAdobeLook() -> AdobeLookXMP? {
        guard let url = AdobeProfileLocator().locateAdobeColorLookXMP() else {
            print("SKIP: Adobe Color.xmpが見つからないため、この環境ではスキップします。")
            return nil
        }
        return try? AdobeLookXMP(contentsOf: url)
    }

    // MARK: - Numeric comparison helpers

    private func approxEqual(_ a: Double, _ b: Double, relTol: Double, absTol: Double) -> Bool {
        if abs(a - b) <= absTol { return true }
        return abs(a - b) <= relTol * max(abs(a), abs(b))
    }

    private func expectApproxEqual(
        _ a: Double, _ b: Double, relTol: Double = 1e-3, absTol: Double = 1e-5, _ tag: String = ""
    ) {
        #expect(approxEqual(a, b, relTol: relTol, absTol: absTol), "\(tag) \(a) vs \(b)")
    }

    private func expectVectorApproxEqual(
        _ actual: SIMD3<Double>, _ expected: [Double], relTol: Double = 1e-3, absTol: Double = 1e-5,
        _ tag: String = ""
    ) {
        expectApproxEqual(actual.x, expected[0], relTol: relTol, absTol: absTol, "\(tag).x")
        expectApproxEqual(actual.y, expected[1], relTol: relTol, absTol: absTol, "\(tag).y")
        expectApproxEqual(actual.z, expected[2], relTol: relTol, absTol: absTol, "\(tag).z")
    }

    private func expectMatrixApproxEqual(
        _ actual: Matrix3x3, _ expectedRows: [[Double]], relTol: Double = 1e-4, absTol: Double = 1e-6,
        _ tag: String = ""
    ) {
        for r in 0..<3 {
            for c in 0..<3 {
                expectApproxEqual(actual[r, c], expectedRows[r][c], relTol: relTol, absTol: absTol, "\(tag)[\(r)][\(c)]")
            }
        }
    }

    private func expectHueSatSamplesMatch(
        _ table: DCPProfile.HueSatTable, _ samples: [HueSatSampleFixture], _ tag: String = ""
    ) {
        for sample in samples {
            let entry = table[sample.val_index, sample.hue_index, sample.sat_index]
            expectApproxEqual(entry.hueShift, sample.hue_shift, relTol: 1e-4, absTol: 1e-6, "\(tag) hueShift")
            expectApproxEqual(entry.satScale, sample.sat_scale, relTol: 1e-4, absTol: 1e-6, "\(tag) satScale")
            expectApproxEqual(entry.valScale, sample.val_scale, relTol: 1e-4, absTol: 1e-6, "\(tag) valScale")
        }
    }

    // MARK: - DCPProfile vs. dcp-panasonic-dc-s5.json

    @Test func dcpTagsAndSamplesMatchFixture() throws {
        guard let dcp = loadRealDCP() else { return }
        let fx = try loadFixture("dcp-panasonic-dc-s5.json", as: DCPFixtureFile.self)

        #expect(dcp.uniqueCameraModel == fx.unique_camera_model)
        #expect(dcp.profileName == fx.profile_name)
        #expect(dcp.calibrationIlluminant1 == fx.calibration_illuminant1)
        #expect(dcp.calibrationIlluminant2 == fx.calibration_illuminant2)
        #expect(dcp.hueSatMapEncoding == fx.hue_sat_map_encoding)
        #expect(dcp.lookTableEncoding == fx.look_table_encoding)
        #expect(dcp.hueSatMapDims == DCPProfile.Dimensions3(
            hue: fx.hue_sat_map_dims_hue_sat_val[0],
            sat: fx.hue_sat_map_dims_hue_sat_val[1],
            val: fx.hue_sat_map_dims_hue_sat_val[2]
        ))
        #expect(dcp.lookTableDims == DCPProfile.Dimensions3(
            hue: fx.look_table_dims_hue_sat_val[0],
            sat: fx.look_table_dims_hue_sat_val[1],
            val: fx.look_table_dims_hue_sat_val[2]
        ))

        if let m = dcp.colorMatrix1 { expectMatrixApproxEqual(m, fx.color_matrix1, "colorMatrix1") }
        else { Issue.record("ColorMatrix1が読めていません") }
        if let m = dcp.colorMatrix2 { expectMatrixApproxEqual(m, fx.color_matrix2, "colorMatrix2") }
        else { Issue.record("ColorMatrix2が読めていません") }
        if let m = dcp.forwardMatrix1 { expectMatrixApproxEqual(m, fx.forward_matrix1, "forwardMatrix1") }
        else { Issue.record("ForwardMatrix1が読めていません") }
        if let m = dcp.forwardMatrix2 { expectMatrixApproxEqual(m, fx.forward_matrix2, "forwardMatrix2") }
        else { Issue.record("ForwardMatrix2が読めていません") }

        if let t = dcp.hueSatMapData1 { expectHueSatSamplesMatch(t, fx.hue_sat_map_data1_samples, "huesat1") }
        else { Issue.record("HueSatMapData1が読めていません") }
        if let t = dcp.hueSatMapData2 { expectHueSatSamplesMatch(t, fx.hue_sat_map_data2_samples, "huesat2") }
        else { Issue.record("HueSatMapData2が読めていません") }
        if let t = dcp.lookTableData { expectHueSatSamplesMatch(t, fx.look_table_samples, "dcpLook") }
        else { Issue.record("LookTableDataが読めていません") }
    }

    // MARK: - AdobeLookXMP vs. adobe-color-look.json

    @Test func adobeLookMatchesFixture() throws {
        guard let look = loadRealAdobeLook() else { return }
        let fx = try loadFixture("adobe-color-look.json", as: AdobeLookFixtureFile.self)

        #expect(look.lookTableID.caseInsensitiveCompare(fx.look_table_id) == .orderedSame)
        #expect(look.lookTableID.caseInsensitiveCompare(fx.inflated_md5) == .orderedSame)
        #expect(look.headerType == fx.header_type)
        #expect(look.headerVersion == fx.header_version)
        #expect(look.dims == DCPProfile.Dimensions3(
            hue: fx.dims_hue_sat_val[0], sat: fx.dims_hue_sat_val[1], val: fx.dims_hue_sat_val[2]
        ))

        expectHueSatSamplesMatch(look.lookTableData, fx.samples, "adobeLook")

        #expect(look.toneCurvePoints.count == fx.tone_curve_points_0_255.count)
        for (point, expected) in zip(look.toneCurvePoints, fx.tone_curve_points_0_255) {
            expectApproxEqual(point.x, expected[0], relTol: 1e-6, absTol: 1e-9, "toneCurve.x")
            expectApproxEqual(point.y, expected[1], relTol: 1e-6, absTol: 1e-9, "toneCurve.y")
        }
    }

    // MARK: - ColorSpec vs. colorspec-cases.json

    @Test func colorSpecMatchesFixtureForAllPhotos() throws {
        guard let dcp = loadRealDCP() else { return }
        let fx = try loadFixture("colorspec-cases.json", as: ColorSpecCasesFixtureFile.self)

        guard let cm1 = dcp.colorMatrix1, let cm2 = dcp.colorMatrix2,
              let illum1 = dcp.calibrationIlluminant1, let illum2 = dcp.calibrationIlluminant2
        else {
            Issue.record("DCPにColorMatrix/CalibrationIlluminantがありません")
            return
        }
        let spec = try ColorSpec(
            colorMatrix1: cm1, colorMatrix2: cm2,
            forwardMatrix1: dcp.forwardMatrix1, forwardMatrix2: dcp.forwardMatrix2,
            calibrationIlluminant1: illum1, calibrationIlluminant2: illum2
        )

        #expect(!fx.photos.isEmpty)
        for (name, photo) in fx.photos {
            let neutralG1 = SIMD3(
                photo.neutral_g1_normalized_rgb[0], photo.neutral_g1_normalized_rgb[1], photo.neutral_g1_normalized_rgb[2]
            )
            let whiteXY = try spec.neutralToXY(neutralG1)
            expectApproxEqual(whiteXY.x, photo.white_xy[0], relTol: 1e-4, absTol: 1e-7, "\(name) white.x")
            expectApproxEqual(whiteXY.y, photo.white_xy[1], relTol: 1e-4, absTol: 1e-7, "\(name) white.y")

            let temperature = DNGTemperature.xyToTemperature(whiteXY)
            expectApproxEqual(temperature, photo.cct_kelvin, relTol: 1e-4, absTol: 1e-3, "\(name) CCT")

            let g = spec.gFraction(white: whiteXY)
            expectApproxEqual(g, photo.g_fraction_stdA_weight, relTol: 1e-4, absTol: 1e-7, "\(name) gFraction")

            let colorMatrixWhite = spec.colorMatrix(white: whiteXY)
            expectMatrixApproxEqual(
                colorMatrixWhite, photo.color_matrix_interpolated_xyz_to_camera, "\(name) colorMatrix"
            )

            let forward = try spec.forwardMatrix(white: whiteXY)
            expectMatrixApproxEqual(
                forward, photo.forward_matrix_interpolated_camera_to_xyzd50, "\(name) forwardMatrix"
            )

            let cameraWhite = AdobeColorSpec.cameraWhite(colorMatrix: colorMatrixWhite, white: whiteXY)
            expectVectorApproxEqual(
                cameraWhite, photo.camera_white_sdk, relTol: 1e-4, absTol: 1e-6, "\(name) cameraWhite"
            )

            let combinedPrototype = try AdobeColorSpec.combinedCameraToLinearProPhoto(
                spec: spec, white: whiteXY, neutralG1: neutralG1, variant: .matchPrototype
            )
            expectMatrixApproxEqual(
                combinedPrototype, photo.combined_matrix_camera_to_linear_prophoto.match_prototype,
                "\(name) combined.matchPrototype"
            )

            let combinedSDK = try AdobeColorSpec.combinedCameraToLinearProPhoto(
                spec: spec, white: whiteXY, neutralG1: neutralG1, variant: .sdkCameraWhite
            )
            expectMatrixApproxEqual(
                combinedSDK, photo.combined_matrix_camera_to_linear_prophoto.sdk_camera_white,
                "\(name) combined.sdkCameraWhite"
            )
        }
    }

    // MARK: - AdobeColorMath vs. stage-samples.json

    @Test func stageSamplesMatchPythonReference() throws {
        guard let dcp = loadRealDCP(), let look = loadRealAdobeLook() else { return }
        let stageFx = try loadFixture("stage-samples.json", as: StageSamplesFixtureFile.self)
        let colorSpecFx = try loadFixture("colorspec-cases.json", as: ColorSpecCasesFixtureFile.self)

        #expect(stageFx.colorimetry_photo == "P1013558")
        guard let photo = colorSpecFx.photos[stageFx.colorimetry_photo] else {
            Issue.record("colorspec-cases.jsonに\(stageFx.colorimetry_photo)がありません")
            return
        }
        let neutralG1 = SIMD3(
            photo.neutral_g1_normalized_rgb[0], photo.neutral_g1_normalized_rgb[1], photo.neutral_g1_normalized_rgb[2]
        )

        // stage-samples.json's M/H/E/... were generated against the
        // prototype's own combined matrix (no SDK camera-white
        // correction), so this specific fixture requires `.matchPrototype`
        // to line up; `colorSpecMatchesFixtureForAllPhotos` above already
        // separately validates `.sdkCameraWhite`.
        // The fixture was generated with the prototype's +0.057 EV; the
        // production calibration table has since moved to 0, so pin the
        // fixture's own value here instead of the table's.
        let assets = try AdobeBaseAssets(
            dcp: dcp, look: look, neutralG1: neutralG1, variant: .matchPrototype, baselineEV: stageFx.baseline_ev
        )
        expectApproxEqual(assets.baselineEV, stageFx.baseline_ev, relTol: 1e-9, absTol: 1e-12, "baselineEV")

        for (index, sample) in stageFx.samples.enumerated() {
            let input = SIMD3(sample.input[0], sample.input[1], sample.input[2])
            let tag = "sample[\(index)]"

            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .matrix, assets: assets), sample.M, "\(tag) M"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .hueSat, assets: assets), sample.H, "\(tag) H"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .exposure, assets: assets), sample.E, "\(tag) E"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .lookDCP, assets: assets), sample.L_dcp, "\(tag) L_dcp"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .lookAdobe, assets: assets), sample.L_adobe, "\(tag) L_adobe"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .acr3Tone, assets: assets), sample.T, "\(tag) T"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .lookToneCurve(.a), assets: assets), sample.C_a, "\(tag) C_a"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .lookToneCurve(.b), assets: assets), sample.C_b, "\(tag) C_b"
            )
            expectVectorApproxEqual(
                AdobeColorMath.evaluate(cameraRGB: input, through: .lookToneCurve(.c), assets: assets), sample.C_c, "\(tag) C_c"
            )

            let final = AdobeColorMath.evaluate(cameraRGB: input, through: .final, assets: assets)
            let clipped = SIMD3(min(max(final.x, 0), 1), min(max(final.y, 0), 1), min(max(final.z, 0), 1))
            let encoded = SIMD3(
                DNGColorSpace.srgbEncode(clipped.x), DNGColorSpace.srgbEncode(clipped.y), DNGColorSpace.srgbEncode(clipped.z)
            )
            let quantized = [encoded.x, encoded.y, encoded.z].map { min(max(Int(($0 * 255.0).rounded()), 0), 255) }
            #expect(quantized == sample.final_srgb8_variant_b, "\(tag) final_srgb8")
        }
    }

    // MARK: - ACR3DefaultToneCurve vs. acr3-default-curve.json

    @Test func acr3TableMatchesFixtureMD5AndSamples() throws {
        let fx = try loadFixture("acr3-default-curve.json", as: ACR3FixtureFile.self)
        #expect(ACR3DefaultToneCurve.table.count == fx.count)

        var bytes = [UInt8]()
        bytes.reserveCapacity(ACR3DefaultToneCurve.table.count * 4)
        for value in ACR3DefaultToneCurve.table {
            let bits = Float(value).bitPattern.littleEndian
            withUnsafeBytes(of: bits) { bytes.append(contentsOf: $0) }
        }
        let digestHex = Insecure.MD5.hash(data: Data(bytes)).map { String(format: "%02x", $0) }.joined()
        #expect(digestHex.caseInsensitiveCompare(fx.md5) == .orderedSame)

        for (indexString, expectedValue) in fx.samples {
            guard let index = Int(indexString) else { continue }
            expectApproxEqual(ACR3DefaultToneCurve.table[index], expectedValue, relTol: 1e-6, absTol: 1e-9, "acr3[\(index)]")
        }
    }

    // MARK: - AdobeProfileLocator

    @Test func locatorReturnsNilForEmptySearchRoots() {
        let locator = AdobeProfileLocator(searchRoots: [])
        #expect(locator.locateDCP(uniqueCameraModel: "Panasonic DC-S5") == nil)
        #expect(locator.locateAdobeColorLookXMP() == nil)
    }

    @Test func locatorFindsRealAssetsAndPrefersAdobeStandard() {
        guard let located = AdobeProfileLocator().locateDCP(uniqueCameraModel: "Panasonic DC-S5") else {
            print("SKIP: Panasonic DC-S5のDCPが見つからないため、この環境ではスキップします。")
            return
        }
        #expect(located.profile.profileName == "Adobe Standard")
        #expect(AdobeProfileLocator().locateAdobeColorLookXMP() != nil)
    }

    // MARK: - Property tests (no external asset needed)

    @Test func identityHueSatMapPreservesInputIn2Point5DTable() {
        let dims = DCPProfile.Dimensions3(hue: 4, sat: 4, val: 1)
        let entries = [DCPProfile.HueSatEntry](
            repeating: DCPProfile.HueSatEntry(hueShift: 0, satScale: 1, valScale: 1), count: 4 * 4 * 1
        )
        let table = DCPProfile.HueSatTable(dims: dims, entries: entries)

        for sample in identityTestSamples {
            let output = HueSatMap.apply(sample, table: table)
            expectVectorApproxEqual(output, [sample.x, sample.y, sample.z], relTol: 1e-9, absTol: 1e-9, "identity2.5D")
        }
    }

    @Test func identityHueSatMapPreservesInputInFullTrilinearTable() {
        let dims = DCPProfile.Dimensions3(hue: 4, sat: 4, val: 3)
        let entries = [DCPProfile.HueSatEntry](
            repeating: DCPProfile.HueSatEntry(hueShift: 0, satScale: 1, valScale: 1), count: 4 * 4 * 3
        )
        let table = DCPProfile.HueSatTable(dims: dims, entries: entries)

        for sample in identityTestSamples {
            let output = HueSatMap.apply(sample, table: table)
            expectVectorApproxEqual(output, [sample.x, sample.y, sample.z], relTol: 1e-9, absTol: 1e-9, "identityTrilinear")
        }
    }

    private var identityTestSamples: [SIMD3<Double>] {
        [
            SIMD3(0.8, 0.3, 0.1), SIMD3(0.1, 0.9, 0.4), SIMD3(0.5, 0.5, 0.5),
            SIMD3(0.0, 0.0, 0.0), SIMD3(1.0, 0.0, 0.0), SIMD3(0.2, 0.2, 0.9),
        ]
    }

    @Test func hueSatMapInterpolatedReturnsEndpointTablesAtExtremes() throws {
        let dims = DCPProfile.Dimensions3(hue: 2, sat: 2, val: 1)
        let table1 = DCPProfile.HueSatTable(dims: dims, entries: [
            .init(hueShift: 10, satScale: 1, valScale: 1), .init(hueShift: 10, satScale: 1, valScale: 1),
            .init(hueShift: 10, satScale: 1, valScale: 1), .init(hueShift: 10, satScale: 1, valScale: 1),
        ])
        let table2 = DCPProfile.HueSatTable(dims: dims, entries: [
            .init(hueShift: -10, satScale: 1, valScale: 1), .init(hueShift: -10, satScale: 1, valScale: 1),
            .init(hueShift: -10, satScale: 1, valScale: 1), .init(hueShift: -10, satScale: 1, valScale: 1),
        ])
        let atOne = try HueSatMap.interpolated(table1, table2, g: 1.0)
        #expect(atOne.entries[0].hueShift == 10)
        let atZero = try HueSatMap.interpolated(table1, table2, g: 0.0)
        #expect(atZero.entries[0].hueShift == -10)
        let atHalf = try HueSatMap.interpolated(table1, table2, g: 0.5)
        expectApproxEqual(atHalf.entries[0].hueShift, 0, absTol: 1e-9, "interpolated midpoint")

        let mismatched = DCPProfile.HueSatTable(
            dims: DCPProfile.Dimensions3(hue: 3, sat: 2, val: 1), entries: Array(repeating: table1.entries[0], count: 6)
        )
        #expect(throws: HueSatMapError.self) {
            _ = try HueSatMap.interpolated(table1, mismatched, g: 0.5)
        }
    }

    @Test func rgbTonePreservesHue() {
        let samples: [SIMD3<Double>] = [
            SIMD3(0.8, 0.3, 0.1), SIMD3(0.2, 0.6, 0.9), SIMD3(0.9, 0.9, 0.2),
            SIMD3(0.9, 0.2, 0.9), SIMD3(0.1, 0.7, 0.7), SIMD3(0.7, 0.7, 0.1),
        ]
        for sample in samples {
            let (hueBefore, satBefore, _) = HueSatMap.rgbToHSV(sample)
            let toned = RGBTone.apply(sample, curve: ACR3DefaultToneCurve.evaluate)
            guard satBefore > 1e-9 else { continue } // hue is undefined (0) for neutral pixels
            let (hueAfter, _, _) = HueSatMap.rgbToHSV(toned)
            expectApproxEqual(hueAfter, hueBefore, relTol: 1e-6, absTol: 1e-6, "hue preserved")
        }
    }

    @Test func rgbToneDegenerateGrayInputDoesNotDivideByZero() {
        let gray = SIMD3(0.5, 0.5, 0.5)
        let toned = RGBTone.apply(gray, curve: ACR3DefaultToneCurve.evaluate)
        let expected = ACR3DefaultToneCurve.evaluate(0.5)
        expectVectorApproxEqual(toned, [expected, expected, expected], relTol: 1e-9, absTol: 1e-9, "gray tone")
    }

    @Test func identitySplineIsIdentityAndUsesFlatExtension() throws {
        let spline = try DNGSpline(points: [(x: 0.0, y: 0.0), (x: 1.0, y: 1.0)])
        for x in stride(from: 0.0, through: 1.0, by: 0.1) {
            expectApproxEqual(spline.evaluate(x), x, relTol: 1e-9, absTol: 1e-9, "identity spline")
        }
        #expect(spline.evaluate(-0.5) == 0.0)
        #expect(spline.evaluate(1.5) == 1.0)
    }

    @Test func splineRejectsDegenerateInput() {
        #expect(throws: RGBToneError.self) {
            _ = try DNGSpline(points: [(x: 0.0, y: 0.0)])
        }
        #expect(throws: RGBToneError.self) {
            _ = try DNGSpline(points: [(x: 0.5, y: 0.0), (x: 0.5, y: 1.0)])
        }
    }

    @Test func base85DecodeKnownVectors() {
        #expect(AdobeLookXMP.decodeBase85ish("00000") == [0, 0, 0, 0])
        #expect(AdobeLookXMP.decodeBase85ish("00001") == [177, 132, 28, 3])
        #expect(AdobeLookXMP.decodeBase85ish("11111") == [45, 0, 38, 3])
        #expect(AdobeLookXMP.decodeBase85ish("0000") == [0, 0, 0]) // 4-char remainder -> 3 bytes
        #expect(AdobeLookXMP.decodeBase85ish("000") == [0, 0]) // 3-char remainder -> 2 bytes
        #expect(AdobeLookXMP.decodeBase85ish("00") == [0]) // 2-char remainder -> 1 byte
        #expect(AdobeLookXMP.decodeBase85ish("0") == []) // lone leftover char -> dropped
        #expect(AdobeLookXMP.decodeBase85ish("0 0\n001") == [177, 132, 28, 3]) // whitespace ignored
        #expect(AdobeLookXMP.decodeBase85ish("vqf00") == [24, 176, 1, 0]) // real Adobe Color.xmp blob prefix
    }

    @Test func dcpProfileRejectsWrongMagic() {
        // Standard TIFF magic (0x002A) rather than DCP's private "RC" marker.
        var bytes: [UInt8] = [0x49, 0x49, 0x2A, 0x00, 8, 0, 0, 0]
        bytes.append(contentsOf: [0, 0]) // IFD entry count = 0, at offset 8
        #expect(throws: DCPProfileError.self) {
            _ = try DCPProfile(data: Data(bytes))
        }
    }

    @Test func adobeBaseCalibrationKnownAndUnknownModels() {
        expectApproxEqual(
            AdobeBaseCalibration.baselineEV(uniqueCameraModel: "Panasonic DC-S5"), 0.0,
            relTol: 1e-9, absTol: 1e-12, "DC-S5 baselineEV"
        )
        #expect(AdobeBaseCalibration.baselineEV(uniqueCameraModel: "Some Unknown Camera") == 0.0)
    }
}

// MARK: - Fixture JSON shapes (test-only Decodable mirrors of Tests/Fixtures/phase1/*.json)

private struct HueSatSampleFixture: Decodable {
    let val_index: Int
    let hue_index: Int
    let sat_index: Int
    let hue_shift: Double
    let sat_scale: Double
    let val_scale: Double
}

private struct DCPFixtureFile: Decodable {
    let unique_camera_model: String
    let profile_name: String
    let calibration_illuminant1: Int
    let calibration_illuminant2: Int
    let color_matrix1: [[Double]]
    let color_matrix2: [[Double]]
    let forward_matrix1: [[Double]]
    let forward_matrix2: [[Double]]
    let hue_sat_map_dims_hue_sat_val: [Int]
    let hue_sat_map_encoding: Int
    let look_table_dims_hue_sat_val: [Int]
    let look_table_encoding: Int
    let hue_sat_map_data1_samples: [HueSatSampleFixture]
    let hue_sat_map_data2_samples: [HueSatSampleFixture]
    let look_table_samples: [HueSatSampleFixture]
}

private struct AdobeLookFixtureFile: Decodable {
    let look_table_id: String
    let inflated_md5: String
    let header_type: Int
    let header_version: Int
    let dims_hue_sat_val: [Int]
    let samples: [HueSatSampleFixture]
    let tone_curve_points_0_255: [[Double]]
}

private struct CombinedMatrixVariantsFixture: Decodable {
    let match_prototype: [[Double]]
    let sdk_camera_white: [[Double]]
}

private struct ColorSpecPhotoFixture: Decodable {
    let neutral_g1_normalized_rgb: [Double]
    let white_xy: [Double]
    let cct_kelvin: Double
    let g_fraction_stdA_weight: Double
    let color_matrix_interpolated_xyz_to_camera: [[Double]]
    let forward_matrix_interpolated_camera_to_xyzd50: [[Double]]
    let camera_white_sdk: [Double]
    let combined_matrix_camera_to_linear_prophoto: CombinedMatrixVariantsFixture
}

private struct ColorSpecCasesFixtureFile: Decodable {
    let photos: [String: ColorSpecPhotoFixture]
}

private struct StageSampleFixture: Decodable {
    let input: [Double]
    let M: [Double]
    let H: [Double]
    let E: [Double]
    let L_dcp: [Double]
    let L_adobe: [Double]
    let T: [Double]
    let C_a: [Double]
    let C_b: [Double]
    let C_c: [Double]
    let final_srgb8_variant_b: [Int]
}

private struct StageSamplesFixtureFile: Decodable {
    let colorimetry_photo: String
    let baseline_ev: Double
    let samples: [StageSampleFixture]
}

private struct ACR3FixtureFile: Decodable {
    let count: Int
    let md5: String
    let samples: [String: Double]
}
