#!/usr/bin/env python3
"""Embed the NIHO preset XMPs in photobench-engine (`builtinPresets`).

Writes Sources/PhotoBenchEngine/BuiltinPresetData.swift: one Swift raw
multi-line string literal per preset, byte for byte the XMP file at the
repository root, so the engine never looks for preset files at run time.
Run it after changing one of the XMPs and commit the result.

    scripts/generate-builtin-presets.py           # (re)write the Swift file
    scripts/generate-builtin-presets.py --check   # fail if it is out of date

`PhotoBenchEngineTests` also compares the embedded text with the XMP files.
"""

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "Sources" / "PhotoBenchEngine" / "BuiltinPresetData.swift"

# (protocol id, display name, repository-root file), in `builtinPresets` order.
PRESETS = [
    ("niho-bluesky2", "bluesky2", "niho-preset bluesky2.xmp"),
    ("niho-colorful", "colorful", "niho-priset_colorful.xmp"),
    ("niho-night", "night", "niho-preset night.xmp"),
    ("niho-pastel", "pastel", "niho-preset pastel.xmp"),
]


def swift_string(value: str) -> str:
    """A plain one-line Swift string literal (ids, names, file names)."""
    if any(ch in value for ch in '"\\\n\r'):
        raise SystemExit(f"unexpected character in {value!r}")
    return f'"{value}"'


def swift_raw_literal(text: str, label: str) -> str:
    """A raw multi-line literal whose value is exactly `text`.

    The closing delimiter sits at column 0, so no indentation is stripped;
    the newline before it is not part of the value, hence the extra one.
    Enough `#`s are used that neither the closing delimiter nor a raw escape
    (`\\#`) can occur inside the text.
    """
    if "\r" in text:
        raise SystemExit(f"{label}: carriage returns would be normalized by Swift; convert the file to LF")
    hashes = 1
    while ('"""' + "#" * hashes) in text or ("\\" + "#" * hashes) in text:
        hashes += 1
    delimiter = "#" * hashes
    return f'{delimiter}"""\n{text}\n"""{delimiter}'


def identifier(name: str) -> str:
    return "".join(ch for ch in name if ch.isalnum()) + "XMP"


def render() -> str:
    lines = [
        "// Generated by scripts/generate-builtin-presets.py from the NIHO preset XMP",
        "// files at the repository root. Do not edit: change the XMP, run the script",
        "// and commit both.",
        "",
        "extension BuiltinPresets {",
        "    static let all: [BuiltinPreset] = [",
    ]
    for index, (preset_id, name, file_name) in enumerate(PRESETS):
        separator = "," if index < len(PRESETS) - 1 else ""
        lines.append(
            "        BuiltinPreset("
            f"id: {swift_string(preset_id)}, name: {swift_string(name)}, "
            f"sourceFileName: {swift_string(file_name)}, xmp: {identifier(name)})"
            f"{separator}"
        )
    lines.append("    ]")
    for preset_id, name, file_name in PRESETS:
        data = (ROOT / file_name).read_bytes()
        text = data.decode("utf-8")
        digest = hashlib.sha256(data).hexdigest()
        lines.append("")
        lines.append(f"    // {file_name} ({len(data)} bytes, sha256 {digest})")
        lines.append(f"    private static let {identifier(name)} = {swift_raw_literal(text, file_name)}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the Swift file is out of date")
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run {Path(__file__).relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(PRESETS)} presets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
