import Foundation

/// Errors raised while reading a `.dcp` (DNG Camera Profile) file.
public enum DCPProfileError: Error, Sendable, Equatable, LocalizedError {
    case notATIFFLikeFile
    case unsupportedByteOrder
    case unexpectedMagic
    case truncated
    case unsupportedFieldType(Int)
    case unexpectedFieldCount(tag: Int, count: Int)

    public var errorDescription: String? {
        switch self {
        case .notATIFFLikeFile: "DCPファイルのバイトオーダーマーカーが不正です。"
        case .unsupportedByteOrder: "ビッグエンディアン(MM)のDCPは未対応です。"
        case .unexpectedMagic: "DCPのマジックバイトが想定外です（'RC'が必要）。"
        case .truncated: "DCPファイルが途中で終端しています。"
        case .unsupportedFieldType(let type): "未対応のTIFFフィールド型です: \(type)"
        case .unexpectedFieldCount(let tag, let count):
            "タグ\(tag)のフィールド要素数が想定外です: \(count)"
        }
    }
}

/// Reads Adobe `.dcp` (DNG Camera Profile) files: a TIFF-like container that
/// swaps the standard TIFF magic (42) for the private "RC" marker so generic
/// TIFF readers refuse to open it as an image (bytes 0-3 == "IIRC" for the
/// little-endian files Adobe ships). The IFD (tag, type, count,
/// value/offset) structure past that marker is standard TIFF.
///
/// Verified against `dng_shared.cpp` / `dng_parse_utils.cpp` /
/// `dng_camera_profile.cpp` in Adobe DNG SDK 1.7.1
/// (`.photobench/engine-research-20260922/dcp-base-prototype/sdk/dng_sdk_1_7_1/dng_sdk/source/`),
/// and cross-checked directly against a real
/// "Panasonic DC-S5 Adobe Standard.dcp" (see
/// `Tests/Fixtures/phase1/dcp-panasonic-dc-s5.json`, generated by the Python
/// prototype's `dcp_parser.py`, which this type is a faithful Swift port of).
///
/// Read-only; never writes. Only little-endian ("II") files are supported,
/// matching every real-world DCP this project has encountered (Adobe always
/// ships "IIRC").
public struct DCPProfile: Sendable, Equatable {
    /// Hue/saturation/value table axis sizes, in the DNG tag order
    /// (hueDivisions, satDivisions, valDivisions).
    public struct Dimensions3: Sendable, Equatable {
        public var hue: Int
        public var sat: Int
        public var val: Int

        public init(hue: Int, sat: Int, val: Int) {
            self.hue = hue
            self.sat = sat
            self.val = val
        }
    }

    /// One entry of a hue/sat/value delta table.
    public struct HueSatEntry: Sendable, Equatable {
        public var hueShift: Double
        public var satScale: Double
        public var valScale: Double

        public init(hueShift: Double, satScale: Double, valScale: Double) {
            self.hueShift = hueShift
            self.satScale = satScale
            self.valScale = valScale
        }
    }

    /// A DNG hue/sat/value delta table (`ProfileHueSatMapData{1,2}` or
    /// `ProfileLookTableData`), stored value-outermost, hue, then saturation
    /// innermost -- the `dng_hue_sat_map` storage convention confirmed by
    /// `dng_camera_profile::ReadHueSatMap`'s nested `for (val) for (hue) for
    /// (sat)` read loop.
    public struct HueSatTable: Sendable, Equatable {
        public var dims: Dimensions3
        /// Flattened row-major in (val, hue, sat) order; count == hue*sat*val.
        public var entries: [HueSatEntry]

        public init(dims: Dimensions3, entries: [HueSatEntry]) {
            self.dims = dims
            self.entries = entries
        }

        public subscript(val: Int, hue: Int, sat: Int) -> HueSatEntry {
            entries[(val * dims.hue + hue) * dims.sat + sat]
        }
    }

    public var uniqueCameraModel: String = ""
    public var profileName: String = ""
    public var colorMatrix1: Matrix3x3?
    public var colorMatrix2: Matrix3x3?
    public var forwardMatrix1: Matrix3x3?
    public var forwardMatrix2: Matrix3x3?
    public var calibrationIlluminant1: Int?
    public var calibrationIlluminant2: Int?
    public var hueSatMapDims: Dimensions3?
    public var hueSatMapData1: HueSatTable?
    public var hueSatMapData2: HueSatTable?
    /// Defaults to 0 ("linear") when the tag is absent, matching the DNG
    /// default and every profile observed in this project so far.
    public var hueSatMapEncoding: Int = 0
    public var lookTableDims: Dimensions3?
    public var lookTableData: HueSatTable?
    public var lookTableEncoding: Int = 0
    /// Raw `ProfileToneCurve` control points (x0,y0,x1,y1,...) if present.
    /// Not used by the phase1 math (the Panasonic DC-S5 Adobe Standard
    /// profile has none), but exposed since the profile can carry one.
    public var profileToneCurve: [Double]?
    public var profileEmbedPolicy: Int?
    public var profileCopyright: String?
    /// Defaults to 0 (no offset) when absent, matching the DNG default.
    public var baselineExposureOffset: Double = 0
    /// Defaults to 0 ("auto") when absent, matching the DNG default.
    public var defaultBlackRender: Int = 0

    public init(contentsOf url: URL) throws {
        try self.init(data: Data(contentsOf: url))
    }

    public init(data: Data) throws {
        let stream = try TIFFStream(data: data)
        let entries = try stream.readIFD(at: stream.ifdOffset)
        var byTag: [Int: TIFFStream.IFDEntry] = [:]
        for entry in entries { byTag[entry.tag] = entry }

        func ascii(_ tag: Int) throws -> String? {
            guard let entry = byTag[tag] else { return nil }
            return try stream.readASCII(entry)
        }
        func doubles(_ tag: Int) throws -> [Double]? {
            guard let entry = byTag[tag] else { return nil }
            return try stream.readNumeric(entry)
        }
        func int(_ tag: Int) throws -> Int? {
            try doubles(tag)?.first.map { Int($0.rounded()) }
        }
        func matrix(_ tag: Int) throws -> Matrix3x3? {
            guard let values = try doubles(tag) else { return nil }
            guard values.count == 9 else {
                throw DCPProfileError.unexpectedFieldCount(tag: tag, count: values.count)
            }
            return Matrix3x3(
                row0: SIMD3(values[0], values[1], values[2]),
                row1: SIMD3(values[3], values[4], values[5]),
                row2: SIMD3(values[6], values[7], values[8])
            )
        }
        func dims3(_ tag: Int) throws -> Dimensions3? {
            guard let values = try doubles(tag), values.count >= 2 else { return nil }
            let hue = Int(values[0].rounded())
            let sat = Int(values[1].rounded())
            let val = values.count > 2 ? Int(values[2].rounded()) : 1
            return Dimensions3(hue: hue, sat: sat, val: val)
        }

        uniqueCameraModel = try ascii(Tag.uniqueCameraModel) ?? ""
        profileName = try ascii(Tag.profileName) ?? ""
        colorMatrix1 = try matrix(Tag.colorMatrix1)
        colorMatrix2 = try matrix(Tag.colorMatrix2)
        forwardMatrix1 = try matrix(Tag.forwardMatrix1)
        forwardMatrix2 = try matrix(Tag.forwardMatrix2)
        calibrationIlluminant1 = try int(Tag.calibrationIlluminant1)
        calibrationIlluminant2 = try int(Tag.calibrationIlluminant2)
        hueSatMapEncoding = try int(Tag.hueSatMapEncoding) ?? 0
        lookTableEncoding = try int(Tag.lookTableEncoding) ?? 0
        profileEmbedPolicy = try int(Tag.profileEmbedPolicy)
        profileCopyright = try ascii(Tag.profileCopyright)
        baselineExposureOffset = try doubles(Tag.baselineExposureOffset)?.first ?? 0
        defaultBlackRender = try int(Tag.defaultBlackRender) ?? 0
        profileToneCurve = try doubles(Tag.profileToneCurve)

        if let dims = try dims3(Tag.hueSatMapDims) {
            hueSatMapDims = dims
            hueSatMapData1 = try Self.readHueSatTable(
                tag: Tag.hueSatMapData1, dims: dims, byTag: byTag, stream: stream
            )
            hueSatMapData2 = try Self.readHueSatTable(
                tag: Tag.hueSatMapData2, dims: dims, byTag: byTag, stream: stream
            )
        }
        if let dims = try dims3(Tag.lookTableDims) {
            lookTableDims = dims
            lookTableData = try Self.readHueSatTable(
                tag: Tag.lookTableData, dims: dims, byTag: byTag, stream: stream
            )
        }
    }

    /// Reads a flat (hueShift, satScale, valScale) triple stream into a
    /// `HueSatTable`, replicating `dng_camera_profile::ReadHueSatMap`'s
    /// nested val/hue/sat read loop and its "skip sat index 0" tag-size
    /// variant (`fooCount == hues*(sats-1)*vals*3`).
    ///
    /// JUDGMENT CALL: every real profile this project has read (including
    /// the Panasonic DC-S5 Adobe Standard DCP checked into
    /// `Tests/Fixtures/phase1/dcp-panasonic-dc-s5.json`) stores the FULL
    /// count, so this "skip sat0" branch is never actually exercised here.
    /// The DNG SDK's own `dng_hue_sat_map::SetDivisions` merely zero-fills
    /// the whole table before `ReadHueSatMap` runs, and the reduced-count
    /// branch of `ReadHueSatMap` never touches sat index 0 at all -- so the
    /// SDK's *literal* behavior for that index would be all-zero
    /// (hueShift=0, satScale=0, valScale=0), which would make every fully
    /// desaturated pixel go black and is almost certainly not what any real
    /// authoring tool intends. This port instead follows the Python
    /// prototype's convention (copy hueShift/satScale from sat index 1,
    /// force valScale=1.0 -- the DNG-spec-implied identity at saturation
    /// zero) since it is the physically sensible reading and this path is
    /// untested in practice either way. Flagged here for whoever next
    /// touches a profile that actually hits this branch.
    private static func readHueSatTable(
        tag: Int, dims: Dimensions3, byTag: [Int: TIFFStream.IFDEntry], stream: TIFFStream
    ) throws -> HueSatTable? {
        guard let entry = byTag[tag] else { return nil }
        let flat = try stream.readNumeric(entry)

        let full = dims.hue * dims.sat * dims.val * 3
        let reduced = dims.hue * (dims.sat - 1) * dims.val * 3
        let skipSat0: Bool
        if flat.count == full {
            skipSat0 = false
        } else if flat.count == reduced {
            skipSat0 = true
        } else {
            throw DCPProfileError.unexpectedFieldCount(tag: tag, count: flat.count)
        }

        var entries = [HueSatEntry](
            repeating: HueSatEntry(hueShift: 0, satScale: 0, valScale: 1),
            count: dims.hue * dims.sat * dims.val
        )
        var cursor = 0
        for val in 0..<dims.val {
            for hue in 0..<dims.hue {
                let satStart = skipSat0 ? 1 : 0
                for sat in satStart..<dims.sat {
                    let index = (val * dims.hue + hue) * dims.sat + sat
                    entries[index] = HueSatEntry(
                        hueShift: flat[cursor], satScale: flat[cursor + 1], valScale: flat[cursor + 2]
                    )
                    cursor += 3
                }
                if skipSat0 {
                    let sat0Index = (val * dims.hue + hue) * dims.sat
                    let sat1Index = sat0Index + 1
                    let sat1 = entries[sat1Index]
                    entries[sat0Index] = HueSatEntry(
                        hueShift: sat1.hueShift, satScale: sat1.satScale, valScale: 1.0
                    )
                }
            }
        }
        return HueSatTable(dims: dims, entries: entries)
    }

    /// DNG/DCP tag codes (from `dng_tag_codes.h`) this reader understands.
    enum Tag {
        static let uniqueCameraModel = 50708
        static let colorMatrix1 = 50721
        static let colorMatrix2 = 50722
        static let calibrationIlluminant1 = 50778
        static let calibrationIlluminant2 = 50779
        static let profileName = 50936
        static let hueSatMapDims = 50937
        static let hueSatMapData1 = 50938
        static let hueSatMapData2 = 50939
        static let profileToneCurve = 50940
        static let profileEmbedPolicy = 50941
        static let profileCopyright = 50942
        static let forwardMatrix1 = 50964
        static let forwardMatrix2 = 50965
        static let lookTableDims = 50981
        static let lookTableData = 50982
        static let hueSatMapEncoding = 51107
        static let lookTableEncoding = 51108
        static let baselineExposureOffset = 51109
        static let defaultBlackRender = 51110
    }
}

/// Minimal little-endian TIFF/IFD reader shared by `DCPProfile`. Only the
/// subset of the TIFF spec DCP files actually use is implemented, but all
/// standard field types are decoded (a real DCP has been observed to use
/// ASCII, SHORT, LONG, SRATIONAL and FLOAT for the tags this project reads;
/// the rest are supported for robustness against other cameras/profiles).
struct TIFFStream {
    let data: [UInt8]
    let ifdOffset: Int

    struct IFDEntry {
        let tag: Int
        let type: Int
        let count: Int
        /// The raw 4-byte value/offset field, exactly as stored on disk.
        let valueOrOffsetBytes: [UInt8]
    }

    init(data: Data) throws {
        let bytes = [UInt8](data)
        guard bytes.count >= 8 else { throw DCPProfileError.truncated }
        guard bytes[0] == 0x49, bytes[1] == 0x49 else {
            if bytes[0] == 0x4D, bytes[1] == 0x4D {
                throw DCPProfileError.unsupportedByteOrder
            }
            throw DCPProfileError.notATIFFLikeFile
        }
        // DCP's private magic: "RC" where standard TIFF has 0x002A.
        guard bytes[2] == UInt8(ascii: "R"), bytes[3] == UInt8(ascii: "C") else {
            throw DCPProfileError.unexpectedMagic
        }
        self.data = bytes
        self.ifdOffset = Int(TIFFStream.readU32(bytes, at: 4))
    }

    static func readU16(_ bytes: [UInt8], at offset: Int) -> UInt16 {
        UInt16(bytes[offset]) | (UInt16(bytes[offset + 1]) << 8)
    }

    static func readU32(_ bytes: [UInt8], at offset: Int) -> UInt32 {
        UInt32(bytes[offset])
            | (UInt32(bytes[offset + 1]) << 8)
            | (UInt32(bytes[offset + 2]) << 16)
            | (UInt32(bytes[offset + 3]) << 24)
    }

    static func readI32(_ bytes: [UInt8], at offset: Int) -> Int32 {
        Int32(bitPattern: readU32(bytes, at: offset))
    }

    func readIFD(at offset: Int) throws -> [IFDEntry] {
        guard offset >= 0, offset + 2 <= data.count else { throw DCPProfileError.truncated }
        let count = Int(Self.readU16(data, at: offset))
        var entries: [IFDEntry] = []
        entries.reserveCapacity(count)
        var pos = offset + 2
        for _ in 0..<count {
            guard pos + 12 <= data.count else { throw DCPProfileError.truncated }
            let tag = Int(Self.readU16(data, at: pos))
            let type = Int(Self.readU16(data, at: pos + 2))
            let entryCount = Int(Self.readU32(data, at: pos + 4))
            let valueBytes = Array(data[(pos + 8)..<(pos + 12)])
            entries.append(IFDEntry(tag: tag, type: type, count: entryCount, valueOrOffsetBytes: valueBytes))
            pos += 12
        }
        return entries
    }

    /// Byte size of one field element for each TIFF type code.
    private static let typeSize: [Int: Int] = [
        1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8,
    ]

    private func resolvedBytes(_ entry: IFDEntry) throws -> ArraySlice<UInt8> {
        guard let size = Self.typeSize[entry.type] else {
            throw DCPProfileError.unsupportedFieldType(entry.type)
        }
        let total = size * entry.count
        if total <= 4 {
            return entry.valueOrOffsetBytes[...]
        }
        let offset = Int(Self.readU32(entry.valueOrOffsetBytes, at: 0))
        guard offset >= 0, offset + total <= data.count else { throw DCPProfileError.truncated }
        return data[offset..<(offset + total)]
    }

    func readASCII(_ entry: IFDEntry) throws -> String {
        let bytes = Array(try resolvedBytes(entry).prefix(entry.count))
        let nul = bytes.firstIndex(of: 0) ?? bytes.count
        return String(decoding: bytes[..<nul], as: UTF8.self)
    }

    /// Decodes any numeric TIFF field type (BYTE, SHORT, LONG, SBYTE,
    /// UNDEFINED, SSHORT, SLONG, RATIONAL, SRATIONAL, FLOAT, DOUBLE) to
    /// `[Double]`, matching the DCP prototype's `dcp_parser.py` behavior.
    func readNumeric(_ entry: IFDEntry) throws -> [Double] {
        guard let size = Self.typeSize[entry.type] else {
            throw DCPProfileError.unsupportedFieldType(entry.type)
        }
        let bytes = Array(try resolvedBytes(entry))
        var values: [Double] = []
        values.reserveCapacity(entry.count)
        for index in 0..<entry.count {
            let offset = index * size
            switch entry.type {
            case 1, 7: // BYTE, UNDEFINED
                values.append(Double(bytes[offset]))
            case 3: // SHORT
                values.append(Double(Self.readU16(bytes, at: offset)))
            case 4: // LONG
                values.append(Double(Self.readU32(bytes, at: offset)))
            case 6: // SBYTE
                values.append(Double(Int8(bitPattern: bytes[offset])))
            case 8: // SSHORT
                values.append(Double(Int16(bitPattern: Self.readU16(bytes, at: offset))))
            case 9: // SLONG
                values.append(Double(Self.readI32(bytes, at: offset)))
            case 5: // RATIONAL
                let num = Self.readU32(bytes, at: offset)
                let den = Self.readU32(bytes, at: offset + 4)
                values.append(den == 0 ? 0 : Double(num) / Double(den))
            case 10: // SRATIONAL
                let num = Self.readI32(bytes, at: offset)
                let den = Self.readI32(bytes, at: offset + 4)
                values.append(den == 0 ? 0 : Double(num) / Double(den))
            case 11: // FLOAT
                values.append(Double(Float(bitPattern: Self.readU32(bytes, at: offset))))
            case 12: // DOUBLE
                var bits: UInt64 = 0
                for byteIndex in 0..<8 {
                    bits |= UInt64(bytes[offset + byteIndex]) << (8 * byteIndex)
                }
                values.append(Double(bitPattern: bits))
            default:
                throw DCPProfileError.unsupportedFieldType(entry.type)
            }
        }
        return values
    }
}
